---
- name: Installing the Apache Webserver
  package:
    name: apache2
    state: latest
    update_cache: yes
  
- name: Update the apache2 port
  lineinfile:
    path: /etc/apache2/ports.conf
    regexp: '^Listen 80$'
    line: 'Listen 8080'
    
- name: Starting the apache webserver as service
  service:
    name: apache2
    state: started